spring:
  application:
    name: normalization-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: normalization-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.log0.normalization_service.kafka.deserializer.RawLogEventDeserializer

    listener:
      ack-mode: manual

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
  

clickhouse:
  url: jdbc:ch://localhost:8123/log0
  username: log0
  password: log0
