spring:
  application:
    name: ingestion-gateway

  kafka:
    bootstrap-servers: localhost:9092
  
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
