spring:
  application:
    name: ingestion-gateway

  kafka:
    bootstrap-servers: localhost:9092
  
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: always

server:
  port: 8080

auth-service:
  base-url: ${AUTH_SERVICE_URL:http://auth-service:8086}
  api-key-cache-ttl-seconds: ${API_KEY_CACHE_TTL:60}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
