spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8084

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
