spring:
  application:
    name: normalisation-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: normalisation-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.log0.normalisation_service.kafka.deserializer.RawLogEventDeserializer

    listener:
      ack-mode: manual

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
